#!/usr/bin/env python3
"""Generate NotChat launcher icons into android/overlay/res from assets/notchat-logo.png.

Outputs (copied over dx's defaults by patch_gradle_project.py):
  mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher.webp            legacy (API<26), rounded square
  mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher_round.webp      legacy round
  mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher_foreground.webp adaptive foreground (108dp)
  mipmap-anydpi-v26/ic_launcher.xml / ic_launcher_round.xml  adaptive icon
  values/notchat_icon.xml                                  background colour #282A36
The source is 256x256 with a white margin around a dark rounded square
(~x34..221, y33..217, corner r~40). Foreground = square interior padded with its
edge colour to fit the safe zone (launcher mask shapes it); legacy = rounded square on transparent.
Re-run after changing the logo:  python3 android/tools/make_launcher_icons.py
"""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets" / "notchat-logo.png"
RES = ROOT / "android" / "overlay" / "res"
BG = "#282A36"
DENS = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}

im = Image.open(SRC).convert("RGBA")
inner = im.crop((48, 46, 207, 205))                                      # full-bleed interior
# Adaptive foreground: pad the interior with its own edge colour (#211A4E) so the
# bubble sits inside the 66dp safe zone of the 108dp layer (circle masks don't clip it).
_n = int(inner.size[0] * 1.25)
fg = Image.new("RGBA", (_n, _n), (33, 26, 78, 255))
fg.paste(inner, ((_n - inner.size[0]) // 2, (_n - inner.size[1]) // 2))

def rounded(img, size, radius_frac=0.2):
    big = img.resize((size * 4, size * 4), Image.LANCZOS)
    # replace white anti-aliased corners: mask with our own rounded rect over the interior colour
    base = Image.new("RGBA", big.size, (0, 0, 0, 0))
    fill = inner.resize(big.size, Image.LANCZOS)
    mask = Image.new("L", big.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big.size[0] - 1, big.size[1] - 1),
                                           radius=int(big.size[0] * radius_frac), fill=255)
    base.paste(fill, (0, 0), mask)
    return base.resize((size, size), Image.LANCZOS)

def circle(size):
    big = inner.resize((size * 4, size * 4), Image.LANCZOS)
    mask = Image.new("L", big.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, big.size[0] - 1, big.size[1] - 1), fill=255)
    out = Image.new("RGBA", big.size, (0, 0, 0, 0))
    out.paste(big, (0, 0), mask)
    return out.resize((size, size), Image.LANCZOS)

for d, s in DENS.items():
    out = RES / f"mipmap-{d}"
    out.mkdir(parents=True, exist_ok=True)
    # legacy 48dp icon: ~44dp artwork with 2dp padding
    n = int(48 * s); pad = int(2 * s)
    leg = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    leg.paste(rounded(inner, n - 2 * pad), (pad, pad))
    leg.save(out / "ic_launcher.webp", "WEBP", lossless=True)
    rnd = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    rnd.paste(circle(n - 2 * pad), (pad, pad))
    rnd.save(out / "ic_launcher_round.webp", "WEBP", lossless=True)
    f = int(108 * s)
    fg.resize((f, f), Image.LANCZOS).save(out / "ic_launcher_foreground.webp", "WEBP", lossless=True)
    print("  icons", out)

any_ = RES / "mipmap-anydpi-v26"
any_.mkdir(parents=True, exist_ok=True)
xml = """<?xml version="1.0" encoding="utf-8"?>
<!-- NotChat adaptive launcher icon (generated by android/tools/make_launcher_icons.py) -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/notchat_icon_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""
(any_ / "ic_launcher.xml").write_text(xml)
(any_ / "ic_launcher_round.xml").write_text(xml)
vals = RES / "values"
vals.mkdir(parents=True, exist_ok=True)
(vals / "notchat_icon.xml").write_text(
    '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    f'    <color name="notchat_icon_background">{BG}</color>\n</resources>\n')
print("  adaptive icon + background", BG)
